version: '2'

services:

  nginx:
      depends_on:
        - php5
        - php7
      build:
        context: ./build/nginx
      privileged: true
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      links:
        - php5
        - php7
      volumes:
        - ${GLOBAL_APP_PATH}/webapps:/data/webapps
        - ${GLOBAL_APP_PATH}/config/nginx/conf.d:/etc/nginx/conf.d
        - ${GLOBAL_APP_PATH}/config/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${GLOBAL_APP_PATH}/config/nginx/fastcgi_web:/etc/nginx/fastcgi_web
        - ${GLOBAL_APP_PATH}/config/nginx/fastcgi_mysql:/etc/nginx/fastcgi_mysql
        - ${GLOBAL_APP_PATH}/logs:/data/logs
        - ${GLOBAL_APP_PATH}/data/nginx/data:/data/data
        - ${GLOBAL_APP_PATH}/data/nginx/cache:/data/cache
      restart: always
      networks:
        - frontend

  php5:
      depends_on:
        - mysql
        - redis
        - memcached
      build:
        context: ./build/php5
      privileged: true
      ports:
        - "9000:9000"
      links:
        - "mysql"
        - "redis"
        - "memcached"
      volumes:
        - ${GLOBAL_APP_PATH}/webapps:/data/webapps
        - ${GLOBAL_APP_PATH}/config/php5/php.ini:/usr/local/etc/php/php.ini
        - ${GLOBAL_APP_PATH}/logs/srv/php5:/data/l/srv/php
      restart: always
      networks:
        - frontend

  php7:
      depends_on:
        - mysql
        - redis
        - memcached
      build:
        context: ./build/php7
      privileged: true
      ports:
        - "9001:9000"
      links:
        - "mysql"
        - "redis"
        - "memcached"
      volumes:
        - ${GLOBAL_APP_PATH}/webapps:/data/webapps
        - ${GLOBAL_APP_PATH}/config/php7/php.ini:/usr/local/etc/php/php.ini
        - ${GLOBAL_APP_PATH}/logs/srv/php7:/data/logs/srv/php
      restart: always
      networks:
        - frontend

  mysql:
      build:
        context: ./build/mysql
      privileged: true
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ${GLOBAL_APP_PATH}/data/mysql:/var/lib/mysql
        - ${GLOBAL_APP_PATH}/config/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        - ${GLOBAL_APP_PATH}/logs/srv/mysql:/var/log/mysql
        - ${GLOBAL_APP_PATH}/config/mysql/backup:/var/backup
        - ${GLOBAL_APP_PATH}/config/mysql/crontabs:/var/spool/cron/crontabs
        - ${GLOBAL_APP_PATH}/config/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      restart: always
      networks:
        - backend

  redis:
      build:
        context: ./build/redis
      privileged: true
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ${GLOBAL_APP_PATH}/config/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ${GLOBAL_APP_PATH}/logs/srv/redis:/var/log/redis
        - ${GLOBAL_APP_PATH}/data/redis:/data
      restart: always
      networks:
        - backend

  memcached:
      build:
        context: ./build/memcached
      privileged: true
      ports:
        - "${MEMCACHED_PORT}:11211"
      volumes:
        - ${GLOBAL_APP_PATH}/logs/srv/memcached:/var/log/memcached
      restart: always
      networks:
        - backend

networks:
  frontend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.28.0.0/16
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 172.29.0.0/16
